spring:
  profiles:
    active: prod
  config:
    import:
      "configserver:http://config-server:8888"

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      retry:
        initial-interval: 3000
        max-interval: 5000
        max-attempts: 5
      name: user-service

    consul:
      host: ${CONSUL_HOST:consul-client}
      port: ${CONSUL_PORT:8500}
      discovery:
        service-name: ${SPRING_APPLICATION_NAME:user-service}
        instance-id: ${spring.application.name:user-service}:${server.port}
        prefer-ip-address: true
        health-check-path: ${MANAGEMENT_ENDPOINT_BASE_PATH:/internal/actuator}/health
        health-check-interval: 10s

springdoc:
  swagger-ui:
    path: /swagger-ui.html
